name: Bug Report
description: File a bug report to help improve Opti.
title: "(bug) "
labels: ["bug"]
assignees:
  - byeoon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain what happened before the bug / crash occurred.
      placeholder: Explain here.
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: OS
      description: What OS were you using?
      options:
        - Android (Jailbroken)
        - Android (Jailed)
        - iOS (Jailbroken)
        - iOS (Jailed)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: loader
    attributes:
      label: Opti Loader
      description: Which way did you load Opti?
      options:
        - OptiXposed (Android)
        - OptiManager (Android)
        - OptiTweak (iOS)
        - Sideloaded w/ other mods (iOS / Android)
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Make sure to follow the code of conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
